version: '2'
services:
    takyly-app:
        image: takyly
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://takyly-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Takyly
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=takyly-elasticsearch:9300
        ports:
            - 8080:8080
    takyly-mongodb:
        extends:
            file: mongodb.yml
            service: takyly-mongodb
    takyly-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: takyly-elasticsearch
